<?xml version="1.0"?>
<!DOCTYPE stock[
<!ELEMENT stock (new-car|used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model,price,mileage,condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
]>
<stock>
  <new-car>
     <model>Renault C6</model>
     <price>13.000$</price>
  </new-car>
   <used-car>
     <model>Renault C6</model>
     <price>2500$</price>
      <mileage>200.000km</mileage>
      <condition>good</condition>
   </used-car>
</stock>
